version: "3.9"

services:
  app:
    security_opt:
      - no-new-privileges:true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
